version: 2
updates:
  - package-ecosystem: "npm"
    # Files stored in repository root
    directory: "/"
    schedule:
      interval: "weekly"
      day: tuesday
      timezone: Africa/Nairobi
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: Africa/Nairobi
