---
$schema: https://json.schemastore.org/prettierrc.json
arrowParens: always
bracketSameLine: false
bracketSpacing: true
editorconfig: true
trailingComma: all
endOfLine: crlf
plugins:
  - prettier-plugin-astro
  - prettier-plugin-svelte
  - prettier-plugin-organize-imports
  - prettier-plugin-tailwindcss
overrides:
  - files: "*.astro"
    options:
      parser: astro
  - files: "*.svelte"
    options:
      parser: svelte
